#! /bin/bash
set -eux

DEBVERSION=1.3.1
DEBFULLNAME="$(git config --get user.name)"
DEBEMAIL="$(git config --get user.email)"

echo "Building $DEBVERSION.de"

docker build --build-arg DEBVERSION=$DEBVERSION --build-arg DEBFULLNAME="$DEBFULLNAME" --build-arg DEBEMAIL="$DEBEMAIL" -t zstd-bundle-deb . ||\
    echo "Failed to build image"
CONTAINER=$(docker create zstd-bundle-deb)
docker cp $CONTAINER:/build/artifacts ./
docker rm $CONTAINER
